# Auto Generated #

FROM openjdk:8-stretch

RUN	\
  apt-get update && apt-get install aria2 rsync --yes && \
  mkdir -p /opt

ENV SBT_VERSION 1.2.8
ENV SBT_COURSIER_VERSION 1.1.0-M14-4

RUN \
  aria2c --max-connection-per-server=4 --min-split-size=1M https://github.com/sbt/sbt/releases/download/v$SBT_VERSION/sbt-$SBT_VERSION.tgz && \
  tar xfz sbt-$SBT_VERSION.tgz -C /opt/ && \
  rm sbt-$SBT_VERSION.tgz && \
  ln -s /opt/sbt/bin/sbt /usr/local/bin/sbt && \
# Install Preloaded
  mkdir -p ~/.ivy2/local && \
  mv /opt/sbt/lib/local-preloaded/* ~/.ivy2/local && \
# Coursier
  if [ "$SBT_COURSIER_VERSION" != "" ]; then \
  	mkdir -p ~/.sbt/1.0/plugins && \
  	echo "addSbtPlugin(\"io.get-coursier\" % \"sbt-coursier\" % \"$SBT_COURSIER_VERSION\")" >> ~/.sbt/1.0/plugins/plugins.sbt && \
  	echo 'classpathTypes += "maven-plugin"' >> ~/.sbt/1.0/sbt-coursier.sbt; \
  fi && \
# Warm Up
  mkdir -p ./app/project ./app/src/main/scala && cd ./app && \
  echo "sbt.version=$SBT_VERSION" >> project/build.properties && \
  echo 'lazy val root = (project in file("."))' >> build.sbt && \
  echo 'case object Temp;' >> src/main/scala/Temp.scala && \
  sbt compile && \
  cd .. && rm -rf ./app

WORKDIR /app

CMD ["sbt"]

